name: Non regression tests for OpenGLCppWrapper
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  non_regression_linux:
    name: Non regression tests on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install wget pkg-config lcov libglew-dev libglfw3-dev libbz2-dev libdw-dev tree
      - name: Checkout OpenGLCppWrapper
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download and compile third parts
        run: |
          make download-external-libs
          make compile-external-libs
      - name: Compile OpenGLCppWrapper as libraries
        run: |
          make -j`nproc`
      - name: Compile OpenGLCppWrapper examples
        run: |
          cd examples
          make -j`nproc`
      - name: Install OpenGLCppWrapper as libraries
        run: |
          sudo make install
          tree /usr/include/OpenGLCppWrapper*
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
#      - name: Do non regression tests
#        run: |
#          cd tests
#          make -j`nproc --all`
#          ./build/OpenGLCppWrapper-UnitTest
      - name: Check if the library can be linked against a project
        run: |
          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
          cd LinkAgainstMyLibs/OpenGL
          make -j`nproc --all`

  non_regression_macos:
    name: Non regression tests on MacOS X
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: |
          brew install glfw glew wget
      - name: Checkout OpenGLCppWrapper
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download and compile third parts
        run: |
          make download-external-libs
          make compile-external-libs
      - name: Compile the OpenGLCppWrapper as libraries
        run: |
          make -j`sysctl -n hw.logicalcpu`
      - name: Compile OpenGLCppWrapper examples
        run: |
          cd examples
          make -j`sysctl -n hw.logicalcpu`
#      - name: Install OpenGLCppWrapper as libraries
#        run: |
#          sudo make install
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
#      - name: Do non regression tests
#        run: |
#          cd tests
#          make -j`nproc --all`
#          ./build/OpenGLCppWrapper-UnitTest
#      - name: Check if the library can be linked against a project
#        run: |
#          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
#          cd LinkAgainstMyLibs/OpenGL
#          make -j`nproc --all`
