name: Compil OpenGLCppWrapper

on:
  push:
    branches:
      - dev-refacto-opengl
      - develop
      - master

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install libglew-dev libglfw3-dev libbz2-dev libdw-dev wget

      - name: Install googletest manually
        run: |
          wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
          tar xf release-1.10.0.tar.gz
          (cd googletest-release-1.10.0 &&
          cmake -DBUILD_SHARED_LIBS=ON . &&
          sudo make install)

      - name: Download Repository
        uses: actions/checkout@v2.3.1
        with:
          submodules: true

      - name: Download and compile third parts
        run: |
          make download-external-libs
          make compile-external-libs

      - name: Compile the project
        run: make -j`nproc`

      - name: Compile examples
        run: (cd examples && make -j`nproc`)

      - name: Run unitary test
        run: (cd tests && make -j`nproc`)

  build-macosx:
    name: MacOS X Build
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: brew install glfw glew wget

      - name: Install googletest manually
        run: |
          wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
          tar xf release-1.10.0.tar.gz
          (cd googletest-release-1.10.0 &&
          cmake -DBUILD_SHARED_LIBS=ON . &&
          sudo make install)

      - name: Download Repository
        uses: actions/checkout@v2.3.1
        with:
          submodules: true

      - name: Download and compile third parts
        run: |
          make download-external-libs
          make compile-external-libs

      - name: Compile the project
        run: make -j`sysctl -n hw.logicalcpu`

      - name: Compile examples
        run: (cd examples && make -j`sysctl -n hw.logicalcpu`)

      - name: Run unitary test
        run: (cd tests && make -j`sysctl -n hw.logicalcpu`)
